-- Schema PostgreSQL untuk Supabase
-- Jalankan file ini di Supabase SQL Editor.

DROP TABLE IF EXISTS fasilitas;
DROP TABLE IF EXISTS smpn;
DROP TABLE IF EXISTS kelurahan;
DROP TABLE IF EXISTS kecamatan;
DROP TABLE IF EXISTS users;

CREATE TABLE kecamatan (
    id_kecamatan integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kecamatan varchar(100) NOT NULL
);

CREATE TABLE kelurahan (
    id_kelurahan integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kelurahan varchar(100) NOT NULL,
    id_kecamatan integer REFERENCES kecamatan(id_kecamatan),
    luas_km2 numeric(10,2),
    jumlah_penduduk integer
);

CREATE TABLE smpn (
    id_sekolah integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_sekolah varchar(200) NOT NULL,
    alamat text,
    id_kelurahan integer REFERENCES kelurahan(id_kelurahan),
    latitude numeric(10,8),
    longitude numeric(11,8),
    jumlah_siswa integer,
    status varchar(50) DEFAULT 'Negeri',
    akreditasi varchar(10)
);

CREATE TABLE fasilitas (
    id_fasilitas integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sekolah integer UNIQUE REFERENCES smpn(id_sekolah) ON DELETE CASCADE,
    laboratorium boolean DEFAULT false,
    perpustakaan boolean DEFAULT false,
    lapangan_olahraga boolean DEFAULT false,
    toilet boolean DEFAULT false
);

CREATE TABLE users (
    id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) UNIQUE,
    email varchar(100) UNIQUE NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(20) DEFAULT 'user'
);

INSERT INTO kecamatan (id_kecamatan, nama_kecamatan) VALUES
(1, 'Ternate Tengah'),
(2, 'Ternate Selatan');

INSERT INTO kelurahan (id_kelurahan, nama_kelurahan, id_kecamatan, luas_km2, jumlah_penduduk) VALUES
(1, 'Tanah Raja', 1, 2.50, 8500),
(2, 'Kampung Pisang', 1, 1.80, 6200),
(3, 'Takoma', 1, 3.20, 7800),
(4, 'Bastiong Talangame', 2, 2.10, 7200),
(5, 'Gambesi', 2, 2.80, 6800);

INSERT INTO smpn (id_sekolah, nama_sekolah, alamat, id_kelurahan, latitude, longitude, jumlah_siswa, status, akreditasi) VALUES
(1, 'SMP Negeri 1 Ternate', 'Jl. Pendidikan No.1, Ternate', 1, 0.79540000, 127.38960000, 850, 'Negeri', 'A'),
(2, 'SMP Negeri 3 Ternate', 'Jl. Gambesi Raya', 5, 0.75730000, 127.36810000, 680, 'Negeri', 'B'),
(3, 'SMP Negeri 4 Ternate', 'Jl. Bastiong No.45', 4, 0.76120000, 127.37140000, 710, 'Negeri', 'A'),
(4, 'SMP Negeri 6 Ternate', 'Jl. Pahlawan Revolusi', 2, 0.79210000, 127.38470000, 620, 'Negeri', 'A'),
(5, 'SMP Negeri 7 Ternate', 'Jl. Raya Takoma', 3, 0.76810000, 127.37920000, 540, 'Negeri', 'B');

INSERT INTO fasilitas (id_sekolah, laboratorium, perpustakaan, lapangan_olahraga, toilet) VALUES
(1, true, true, true, true),
(2, true, true, true, true),
(3, true, true, true, true),
(4, true, true, true, true),
(5, true, true, true, true);

INSERT INTO users (id_user, username, email, password, role) VALUES
(3, 'admin', 'admin@webgis.com', '$2y$10$W/orMMb8W28NZIjSf1OEKeqLI2umvPcdPVQQqPm0.56WJnQsYfnVm', 'admin'),
(4, 'user', 'user@webgis.com', '$2y$10$xwX6FTYCftY48pXP5g7Y7O.i0vmeghtbKMU6.xKSucZ5cY1xIUYW6', 'user');

SELECT setval(pg_get_serial_sequence('kecamatan', 'id_kecamatan'), COALESCE((SELECT max(id_kecamatan) FROM kecamatan), 1), true);
SELECT setval(pg_get_serial_sequence('kelurahan', 'id_kelurahan'), COALESCE((SELECT max(id_kelurahan) FROM kelurahan), 1), true);
SELECT setval(pg_get_serial_sequence('smpn', 'id_sekolah'), COALESCE((SELECT max(id_sekolah) FROM smpn), 1), true);
SELECT setval(pg_get_serial_sequence('fasilitas', 'id_fasilitas'), COALESCE((SELECT max(id_fasilitas) FROM fasilitas), 1), true);
SELECT setval(pg_get_serial_sequence('users', 'id_user'), COALESCE((SELECT max(id_user) FROM users), 1), true);
